title: DYING WISH
trigger: If a non-exiled survivor the player controls is killed
context: You look up at the faces gathered around you. It's your life that's
  ending, yet your heart mourns for them. They look so scared. "I know I'm
  dying," you say in a weak voice. "But that's okay. Don't let it slow you down.
  If they didn't end, our lives would have no meaning. You still have so much to
  do. So much to fight for. It's easy to feel lost in a world that seems like
  it's rotting, but really, our lives never had more purpose than they do now.
  So please, for me, stop and think about what you are doing here. What is it
  that you want? Don't waste any more time. Find out what it is, then take hold
  of it and never let go."
result: Build a new set of secret objectives using the secret objective setup
  rules on page 6, section 4, of the rulebook. Each player may choose to remove
  their secret objective from the game without revealing it and draw a new
  secret objective.
