title: I'LL SHOW THEM I CAN HELP!
trigger: If a player is accused of being a betrayer and there is at least 1
  helpless survivor at the colony (a casual accusation is enough)
context: >-
  Once again, a loudmouth is accusing someone else of betrayal. However, the
  next morning, the accused is found dead. "Who did this?!" you demand. "Me,"
  says a meek child in the crowd. 

  "I. . . I saved everybody, didn't I?" Kill the leader of the player that was being accused of being a betrayer. Every non-exiled player must vote with a thumbs up or down. The option with the most votes takes effect.
options:
  - action: The fault doesn't lay with the child, but the accuser.
    result: Immediately Exile the player that made the accusation.
  - action: The child is exiled from the colony.
    result: Remove 1 helpless survivor and lose 1 morale.
  - action: If the colony votes for the thumbs down option, any player may choose to
      have this option trigger instead. "Monsters! I'll not leave her to die out
      there."
    result: The player that chose to trigger this option must remove a survivor they
      control and a helpless survivor from the game. No morale is lost.
vote: true
