title: INTERVENTION
trigger: If a non-exiled survivor the player controls has 1 or more despair tokens
context: "\"I've gathered everyone here to let you know we care about you. We
  know what you've been through, and we hurt with you. So tonight's for you.
  Joel found coffee and we know how you used to be way into coffee. Linda
  prepared some of those frozen steaks we found. Remember telling Jason your
  favorite song was 'Hey Jude?' He's been learning it on the guitar ever
  since.\" You're overwhelmed by this act of kindness, and the tears come almost
  as soon as the pick touches guitar strings. So stupid. This kind of emotion
  doesn't have a place in the world anymore, does it? You shake as your friends
  embrace you. This is why I go on, you think."
result: Remove all despair tokens from all survivors you control. Every player
  may give you an item card to add to your hand. Each player that does removes
  all despair tokens from every survivor they control.
