title: JAMIE GILMOUR
trigger: If Jamie is in play and is not exiled
context: "\"Whoa, guys? What's going on?\" The gathered mob presses around.
  \"We're tired of your snooping,\" someone snarls. \"What? Snooping? Guys I
  don't know what you're talking about, can we just-\" The empty can tossed
  against her head cuts her short. \"Let's see how much you enjoy having your
  secrets exposed in front of everybody,\" one of her assailants snarls."
result: In turn order, each player that has had their hand looked at by the
  player that controls Jamie must take a card from the hand of the player that
  controls Jamie. If that player runs out of cards, place 1 wound on Jamie for
  each player that was supposed to take a card but couldn't.
