title: FLIER
trigger: If the player controls a survivor at the colony
context: Strong winds in the evening yielded a strange surprise when the sun
  rose.  Fliers printed on bright orange paper covered the ground, and more were
  struck in the surrounding trees, flapping there like dying birds.  NO HELP
  COMING read the header, making the rest of the flier seem redundant.  A last
  act of the government, it served both as a warning and a catalog of their
  failed attempts at combatting the dead.  NO HELP COMING.  Welcome to the new
  normal.
result: '"This doesn''t have to break us.  It was naive for us to ever have
  thought that help was on the way.  We can lie down and die or we can hunker
  down for the long haul and outlast this." At the end of the next round, if
  there is not at least 1 barricade at each location, lose 1 morale.  If there
  are 2 or more barricades at each location, gain 1 morale.'
