title: LIGHTHOUSE
trigger: If a survivor the player controls is at the colony
context: '"Remember how that fire drew in all those zombies last week?  Well
  the other day I was looking out at the lighthouse and had an idea.  What if we
  fired that thing up to lure away the dead?  It hasn''t seen full use in
  decades, but they''d light it up every now and then for special occasions, so I
  don''t think it can be in that bad of shape."'
result: You may move 1 action die from your unused action die pool to your used
  action die pool to remove 1 zombie from every location. If you do not, nothing
  happens.
