title: WELCOME HOME
trigger: If the player moves a survivor
context: Oh God.  This is the street your parent's lived on.  How changed is the
  world that you didn't recognize it?  And now you can't stop yourself  you have
  to know.  You turn from your intended destination, and soon open the back door
  to their house.  The smell that assaults you warns of what awaits, but still
  you enter.  You find your mother in the living room, face down on the
  floor.  Her head is a halo of dried gore and your father's Colt lies next to
  her.  You don't even have a chance to mourn before the thing that was your
  father comes crawling down the stairs.
options:
  - action: You dive for the gun and take aim.
    result:
      You struggle to pull the trigger, but soon he's right on top of you, his
      hands scrabbling at your feet.  "I'm sorry Poppa."  Roll once for exposure
      on the moved survivor.  If the survivor isn't killed attach this card to
      it.  Once per round when this survivor performs an attack do not roll for
      exposure.
  - action:
      You run out the house and don't look back.  There was no way you could
      have shot him.
    result: Nothing happens.
