title: DROP OUT
trigger: If at any time the player rolls a die and it falls off the playing surface
context: Whenever you notice something bright and colorful you almost feel
  embarrassed for it, like it's wearing the fashion of another era.  The Earth
  is bleached and dead, and the more time you spend out in the wilds searching
  for some trivial scrap that will make life only moderately more sustainable,
  the more you feel like a fool. No more. Caring seems as passe as color, and
  you're done with it.
options:
  - action: '"I''m going off on my own for a while. Whatever happens, happens."'
    result: Take a survivor you control and shuffle it back into the survivor
      deck.  Remove the standee from the board.
  - action: '"I need a break.  Maybe it''s time for a ''workplace injury''".'
    result: Choose a survivor and roll the exposure die for them.  The chosen
      survivor suffers the result.  If the survivor receives a wound but is not
      killed, shuffle its card back into the survivor deck.  Remove its standee
      from the board and place a helpless survivor token at the colony.
