title: RICH SOMMER
trigger: If Rich Sommer is currently in the survivor deck and there is at least
  1 helpless survivor
context: >-
  A man rides up on a motorcycle with a chainsaw strapped to his back. At first
  you think he's a raider, but he gives the lookout a friendly thumbs up. "Hey
  gang, how about letting me join your colony?" he calls out. 

  "Ommagawd, that's Rich Sommer!" blurts One-Eyed Sue. "He's been on the TV!" %% "Never heard of him," you say. The man laughs it off. %% "No, I get that all the time. I'm just some guy," he says. %% "You look just like him," Sue insists. %% "I'm just a regular Joe in a zombie apocalypse, who enjoys doing things people who aren't celebrities do," assures the man. %% "Why you getting shy TV man?" Sue demands, and she begins quoting lines from some show.
options:
  - action: You egg Sue on and toss empty beer cans at the man.
    result: He rides off in disgust. Nothing happens.
  - action: You let him in.
    result: Add Rich Sommer to your following. "He sleeps with me," Sue insists.
      Place 1 despair token on Rich Sommer.
