title: "#BIGPHARMAFAIL"
trigger: If a survivor the player controls has 1 or more pill effects equipped
context: One minute you're feeling fine and the next you're lying on the ground,
  screaming, and desperately clutching your butt while your bowels revolt. You
  try to call for help, but all that comes out is a pitiable squeal, and
  suddenly the shadows in the room spring to life and begin dancing around you.
  "Gotta lay off the pills," you gasp. "Lay off the pills?" asks a shadow. "Aw
  baby, the only thing that's gonna fix you is more pills. And aardvark
  insurance. You insured your aardvark, didn't you baby?"
result: At the beginning of every round, replace 1 of the pill effects equipped
  to a survivor you control with a random pill effect from the Raxxon side
  effect deck. If the last one equipped was on its positive side, equip the new
  one on the negative side. If the last one equipped was on its negative side,
  equip the new one on the positive side.
