title: BLUE
trigger: If Blue shares a location with another survivor
context: Look at Barry. Stupid face Barry. Barry has all the bananas. Barry just
  rolling in bananas, and Barry won't share bananas with Blue.  Until Barry
  share bananas, Blue drag Barry to hell.
result: '"She''s not just a harmless chimp, I''m telling you! That freaking ape
  is psycho! Last night I woke up and she was just sitting there in the dark,
  staring at me." The player that controls Blue must place this card by the
  card of a survivor that shares a location with Blue. That survivor is now
  "Barry." If at any point Blue and Barry are the only survivors at a
  location, the player controlling Barry must give a food card to the player
  controlling Blue, or receive 1 despair token. If Blue dies, remove all despair
  tokens from Barry and discard this card.'
